### ISSUE TITLE
It ignores  the env variables

### ISSUE THREAD

**Issue by vporton** [dfinity/vscode-motoko#333]
I start Code with
```
MOPS_ENV=local code
```

But the Code does not use MOPS_ENV environment variable for interactive syntax checking compatible with MOPS. This is a bug, env vars should be taken into account.

Or maybe, it does not invoke `mops sources` at all in interactive syntax checker?

MOPS should be invoked like:

```
MOPS_ENV=local mops sources
```

Ubuntu Linux.

For your reference, `mops.toml`:

```toml
[package]
name = "package_manager"
version = "1.0.0"
description = ""
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
env = "./env-{MOPS_ENV}"
base = "0.14.0"
stable-rbtree = "1.0.0"
itertools = "0.2.2"
assets-api = "1.0.1"
"encoding.mo" = "https://github.com/aviate-labs/encoding.mo#master@2711d18727e954b11afc0d37945608512b5fbce2"
ordered-map = "0.2.2"
ic = "2.0.0"
sha2 = "0.1.0"
concurrent = "0.1.2"
stableheapbtreemap = "1.5.0"
test = "2.1.0"
icrc1-types = "1.0.0"
```
